# Generated by Django 4.0.4 on 2022-04-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('inventory_id', models.CharField(max_length=200)),
                ('purchased_at', models.DateField()),
            ],
        ),
    ]
