services:
  app:
    build: .
    volumes:
      - "./:/app"
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    volumes:
      - "./data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: secret
